// <auto-generated />
using System;
using GulfInfoTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GulfInfoTracker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303171020_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CredibilityReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CredibilityScore")
                        .HasColumnType("int");

                    b.Property<bool>("FullText")
                        .HasColumnType("bit");

                    b.Property<string>("HeadlineAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadlineEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamedEntitiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScoringAttempts")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SummaryAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Translated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("CredibilityScore");

                    b.HasIndex("IngestedAt");

                    b.HasIndex("PluginId");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.ArticleTopic", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArticleId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("ArticleTopics");
                });

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.SourcePollLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticlesIngested")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PolledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SourcePollLogs");
                });

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "T1",
                            LabelAr = "السياسة والحكومة",
                            LabelEn = "Politics & Government"
                        },
                        new
                        {
                            Id = "T2",
                            LabelAr = "الاقتصاد والمالية",
                            LabelEn = "Economy & Finance"
                        },
                        new
                        {
                            Id = "T3",
                            LabelAr = "الطاقة والنفط",
                            LabelEn = "Energy & Oil"
                        },
                        new
                        {
                            Id = "T4",
                            LabelAr = "الأعمال والاستثمار",
                            LabelEn = "Business & Investment"
                        },
                        new
                        {
                            Id = "T5",
                            LabelAr = "الصراع الإيراني / الإسرائيلي / الأمريكي",
                            LabelEn = "Iran / Israel / US Conflict"
                        });
                });

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.ArticleTopic", b =>
                {
                    b.HasOne("GulfInfoTracker.Api.Data.Entities.Article", "Article")
                        .WithMany("ArticleTopics")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GulfInfoTracker.Api.Data.Entities.Topic", "Topic")
                        .WithMany("ArticleTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.Article", b =>
                {
                    b.Navigation("ArticleTopics");
                });

            modelBuilder.Entity("GulfInfoTracker.Api.Data.Entities.Topic", b =>
                {
                    b.Navigation("ArticleTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
